import type { Metadata } from "next";

import { storyblokInit, apiPlugin } from "@storyblok/react/rsc"
import StoryblokProvider from '@/helpers/StoryblockProvider';
import StyledComponentsRegistry from "@/helpers/StyledComponentsRegistry";
import { montserrat, notoSerif } from '@/styles/fonts';
import '@/styles/globals.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  // themeColor: '#ffffff', - unsupported error?
  // TODO: don't see these are added??
  icons: [
    {
      url: '/favicons/apple-touch-icon.png',
      rel: 'apple-touch-icon',
      sizes: '180x180',
    },
    {
      url: '/favicons/favicon-32x32.png',
      rel: 'icon',
      sizes: '32x32',
      type: 'image/png',
    },
    {
      url: '/favicons/favicon-16x16.png',
      rel: 'icon',
      sizes: '16x16',
      type: 'image/png',
    },
    {
      url: '/favicons/site.webmanifest',
      rel: 'manifest',
    },
    {
      url: '/favicons/safari-pinned-tab.svg',
      rel: 'mask-icon',
      color: '#005807',
    },
  ]
};

storyblokInit({
  accessToken: process.env.storyblokApiToken,
  use: [apiPlugin],
  apiOptions: {
    region: 'us', // TODO: how to change this to ca?
  },
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoryblokProvider>
      <html lang="en">
        <body className={`${montserrat.variable} ${notoSerif.variable}`}>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </body>
      </html>
    </StoryblokProvider>
  )
}
